[versions]
ksp = "1.8.0-1.0.9"
kotlin = "1.8.0"
androidGradlePlugin = "7.4.1"
kotlinter = "3.13.0"

desugaring = "2.0.0"

kotlinxDateTime = "0.4.0"
kotlinCoroutines = "1.6.4"
kotlinxSerialization = "1.4.0"

koin = "3.3.2"
koin-android= "3.3.2"
koin-android-compose= "3.4.1"
koin-ksp = "1.1.0"

coil = "2.2.0"

paging = "3.1.1"
pagingCompose = "1.0.0-alpha17"
retrofit = "2.9.0"
okHttp = "4.10.0"

kodeinDB = "0.9.0-beta"

composeBom = "2023.01.00"
composeCompiler = "1.4.0"
composeActivity = "1.6.1"
accompanist = "0.28.0"

androidxLifecycle = "2.5.1"
navigation = "2.5.1"
coreKtx = "1.8.0"
appcompat = "1.5.0"
startup = "1.1.0"

material = "1.6.1"
constraintLayout = "1.0.1"
lottie = "5.2.0"
fluentIcons = "1.1.192"
splashScreen = "1.0.0"
glance = "1.0.0-alpha05"

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
gradlePlugin-kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-ktlint = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }
gradlePlugin-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp"}

accompanist-flowLayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-appWidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-test = { group = "androidx.compose.ui", name = "ui-test" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-uiTest = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-uiUtil = { group = "androidx.compose.ui", name = "ui-util" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-ksp" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }

kodeindb-debug = { module = "org.kodein.db:kodein-db-android-debug", version.ref = "kodeinDB" }
kodeindb-kotlinx-serializer = { module = "org.kodein.db:kodein-db-serializer-kotlinx", version.ref = "kodeinDB" }
kodeindb-release = { module = "org.kodein.db:kodein-db-android", version.ref = "kodeinDB" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlinx-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
kotlinx-serializationCbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

material3 = { module = "com.google.android.material:material", version.ref = "material" }
fluentIcons = { module = "com.microsoft.design:fluent-system-icons", version.ref = "fluentIcons" }
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
paging = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }


test-core = { module = "androidx.test:core", version = "1.4.0" }
test-rules = { module = "androidx.test:rules", version = "1.4.0" }
test-junit = { module = "junit:junit", version = "4.13" }
test-junit-ext = { module = "androidx.test.ext:junit-ktx", version = "1.1.2" }
test-espressoCore = { module = "androidx.test.espresso:espresso-core", version = "3.3.0" }

jdkDesugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.1" }
ktorUtils = { module = "io.ktor:ktor-utils", version = "2.1.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
