[versions]
ksp = "1.8.22-1.0.11"
kotlin = "1.8.22"
androidGradlePlugin = "8.1.0"
kotlinter = "3.14.0"
ktorfitGradle = "1.0.0"
kotlinxAtomic = "0.21.0"
composeMultiplatform = "1.4.3"

# common
androidxLifecycle = "2.6.1"
androidxAnnotations = "1.7.0-alpha03"
androidxDatastore = "1.1.0-alpha04"
androidxCollections = "1.3.0-alpha04"

composeBom = "2023.06.01"
composeMaterial2 = "1.4.3"
composeCompiler = "1.4.8"

kotlinxDateTime = "0.4.0"
kotlinCoroutines = "1.7.3"
kotlinxSerialization = "1.5.1"

koin = "3.4.2"
koinCompose = "1.0.3"
koinKsp = "1.2.2"

ktorfit = "1.4.3"
ktor = "2.3.2"

mokoResourcesVersion = "0.23.0"

imageLoader = "1.6.0"
insetsx = "0.1.0-alpha10"

uuid = "0.7.0"
kermit = "2.0.0-RC5"

paging = "3.2.0-alpha05-0.2.2"
pagingCompose = "3.2.0-alpha05-0.2.2"

# android only
materialView = "1.9.0"
splashScreen = "1.0.1"
glance = "1.0.0-rc01"
google-maps-compose = "2.11.1"
play-service-maps = "18.1.0"
koinAndroid = "3.4.2"

composeActivity = "1.7.2"
coreKtx = "1.10.1"
appcompat = "1.6.1"
startup = "1.1.1"
lottie = "6.0.0"
fluentIcons = "1.1.192"


[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-ktlint = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }
gradlePlugin-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp"}
gradlePlugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
gradlePlugin-mokoResources = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResourcesVersion" }

# Common
androidx-datastore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidxDatastore" }
androidx-collections = { module = "androidx.collection:collection", version.ref = "androidxCollections" }
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotations" }

composeMP-utils = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "composeMultiplatform" }

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial2" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-test = { group = "androidx.compose.ui", name = "ui-test" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-uiTest = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-uiUtil = { group = "androidx.compose.ui", name = "ui-util" }

imageLoader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }
insetsx = { module = "com.moriatsushi.insetsx:insetsx", version.ref = "insetsx" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinKsp" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinKsp" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlinx-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
kotlinx-serializationCbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-atomic = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomic" }

moko-resources = { module = "dev.icerock.moko:resources", version.ref = "mokoResourcesVersion" }
moko-resourcesCompose = { module = "dev.icerock.moko:resources-compose", version.ref = "mokoResourcesVersion" }
moko-resourcesTest = { module = "dev.icerock.moko:resources-test", version.ref = "mokoResourcesVersion" }

uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorUtils = { module = "io.ktor:ktor-utils", version = "2.3.1" }

paging = { module = "app.cash.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "pagingCompose" }

# Android
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-appWidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }

google-maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "google-maps-compose" }
gms-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-service-maps" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }

material3 = { module = "com.google.android.material:material", version.ref = "materialView" }

fluentIcons = { module = "com.microsoft.design:fluent-system-icons", version.ref = "fluentIcons" }
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }


test-core = { module = "androidx.test:core", version = "1.5.0" }
test-rules = { module = "androidx.test:rules", version = "1.5.0" }
test-junit = { module = "junit:junit", version = "4.13.2" }
test-junit-ext = { module = "androidx.test.ext:junit-ktx", version = "1.1.5" }
test-espressoCore = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfitGradle" }
kotlinx-atomic = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
#libres = { id = "io.github.skeptick.libres", version.ref = "libres" }
#buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
