package io.edugma.domain.base.utils

/**
 * Returns a [List] containing each original element, with an optional separator
 * generated by [generator], given the elements before and after (or null, in boundary
 * conditions).
 *
 * Note that this transform is applied asynchronously, as pages are loaded. Potential
 * separators between pages are only computed once both pages are loaded.
 *
 */
fun <T : R, R : Any> List<T>.insertSeparators(
    generator: (T?, T?) -> R?
): List<R> {
    return asSequence()
        .run {
            if (this@insertSeparators.isEmpty()) {
                this
            } else {
                sequenceOf(null) + this + null
            }
        }
        .zipWithNext()
        .flatMap {
            listOf(
                it.first,
                generator(it.first, it.second)
            )
        }.filterNotNull()
        .toList()
}