package io.edugma.features.base.core.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0062a1)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcfe5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
val md_theme_light_secondary = Color(0xFF744b9c)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf1daff)
val md_theme_light_onSecondaryContainer = Color(0xFF2c0052)
val md_theme_light_tertiary = Color(0xFF9f4100)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdbc9)
val md_theme_light_onTertiaryContainer = Color(0xFF341000)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFF99cbff)
val md_theme_light_shadow = Color(0xFF000000)


val md_theme_light_success = Color(0xFF006e00)
val md_theme_light_successContainer = Color(0xFF75ff64)
val md_theme_light_onSuccess = Color(0xFFFFFFFF)
val md_theme_light_onSuccessContainer = Color(0xFF002200)



val md_theme_dark_primary = Color(0xFF99cbff)
val md_theme_dark_onPrimary = Color(0xFF003256)
val md_theme_dark_primaryContainer = Color(0xFF00497a)
val md_theme_dark_onPrimaryContainer = Color(0xFFcfe5ff)
val md_theme_dark_secondary = Color(0xFFdfb7ff)
val md_theme_dark_onSecondary = Color(0xFF441a6b)
val md_theme_dark_secondaryContainer = Color(0xFF5c3383)
val md_theme_dark_onSecondaryContainer = Color(0xFFf1daff)
val md_theme_dark_tertiary = Color(0xFFffb68f)
val md_theme_dark_onTertiary = Color(0xFF562000)
val md_theme_dark_tertiaryContainer = Color(0xFF7a3000)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdbc9)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF0062a1)
val md_theme_dark_shadow = Color(0xFF000000)


val md_theme_dark_success = Color(0xFF57e24a)
val md_theme_dark_successContainer = Color(0xFF005300)
val md_theme_dark_onSuccess = Color(0xFF003a00)
val md_theme_dark_onSuccessContainer = Color(0xFF75ff64)


val seed = Color(0xFF6178ff)
val error = Color(0xFFba1b1b)